#!/usr/bin/env bash
alias ..="cd .."            # Up one level
alias ...="cd ../.."        # Up two levels
alias ....="cd ../../.."    # Up three levels


# General
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias ls="ls -Al"
alias h=history
alias e="$EDITOR"
alias v="$VISUAL"
alias eb='e ~/.zshrc'
alias rb='source ~/.zshrc'
alias f='open -a Finder ./'
alias c='clear'
alias cm='chezmoi'
alias vi=nvim
alias vim=nvim
alias tm='[ -z "$TMUX" ] && { tmux attach || exec tmux new-session && exit;}'

# Git
alias ga="git add"
alias gall="git add --all"
alias gb="git branch"
alias gba="git branch --all"
alias gc="git commit"
alias gca="git commit --amend"
alias gcl="git clone --recursive"
alias gco="git checkout"
alias gcp="git cherry-pick"
alias gd="git diff"
alias grd="git --no-pager diff"
alias gf="git fetch --dry-run --verbose"
alias gg="git grep"
alias gge="git grep -P"
alias ggei="git grep -Pi"
alias gl="git log --oneline -n 10"
alias gp="git push"
alias gpl="git pull"
alias grb="git rebase"
alias gs="git status -sb"

# Caddy
alias run-caddy-fileserver="caddy file-server --listen :2015 --browse"

# Microsoft Defender
alias unload-ms-defender="sudo launchctl unload /Library/LaunchDaemons/com.microsoft.fresno.plist && sudo launchctl unload /Library/LaunchDaemons/com.microsoft.fresno.uninstall.plist"

# Kubernetes
alias k="kubectl"
alias kctx="kubectx"
alias kns="kubens"

# Ssh
# alias compile-ssh-config="echo -n > ~/.ssh/config && cat ~/.ssh/ssh-configs/*.config > ~/.ssh/config"
# alias ssh="compile-ssh-config && ssh"
alias copy_ssh="pbcopy < ~/.ssh/id_rsa.pub"

# Meld
alias meld="/Applications/Meld.app/Contents/MacOS/Meld"

# Docker
alias dc="docker-compose $1"
alias drit="docker run -it --rm ${1} /bin/bash"
alias dr="docker run ${1}"
alias dp="docker system prune"
alias dpa="docker system prune -a"
alias dcs="docker context use ${1}"
alias dcl="docker context list"

# Git
alias lg="lazygit"

# Util
alias reset-terminal="stty sane"
alias reset-audio="sudo killall coreaudiod"

# Terraform
alias tf="terraform"
alias tg="terragrunt"

# CleanUp
alias cleanupDS="find . -type f -name '*.DS_Store' -ls -delete"

# Process and Networking
alias myip='curl ip.appspot.com'                    # myip:         Public facing IP Address
alias lsock='sudo /usr/sbin/lsof -i -P'             # lsock:        Display open sockets
alias openPorts='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections

# Brew update
alias brew-update='brew update && brew upgrade && brew upgrade --cask && brew cleanup'
alias brew-backup='cd ~/.brew/backup && rm -f Brewfile && brew bundle dump && cd -'
alias brew-backup-restore='cd ~/.brew/backup/brew/ && brew bundle && cd -'

# System update
alias system-update='brew-update && tldr --update && kubectl krew upgrade && zimfw upgrade'

# Assume
alias assume="source assume"
