#+TITLE: Doom Emacs configuration
#+AUTHOR: Marco Pas
#+EMAIL: marco.pasopas@gmail.com
#+EXPORT_FILE_NAME: README.md
#+PROPERTY: header-args:emacs-lisp :tangle config.el
#+STARTUP: fold

* Table of Contents                                                                                             :TOC_3:noexport:
- [[#references][References]]
  - [[#config-file-headers][Config file headers]]
  - [[#customized-variables][Customized variables]]
- [[#global-constants][Global constants]]
  - [[#directories][Directories]]
- [[#personal-information][Personal Information]]
  - [[#set-full-name][Set full name]]
  - [[#set-email-address][Set email address]]
- [[#general-configuration][General configuration]]
  - [[#set-the-authentication-source-to-use][Set the authentication source to use]]
  - [[#disable-exit-confirmation][Disable exit confirmation]]
  - [[#keybindings][Keybindings]]
    - [[#remove-entire-line-when-at-the-beginning-c-k][Remove entire line when at the beginning =C-k=]]
    - [[#closes-the-current-buffer-c][Closes the current buffer =C=]]
    - [[#cycle-through-the-open-windows-c-w-c-w][Cycle through the open windows =C-w C-w=]]
    - [[#grab-open-link-from-application-c-c-g][Grab open link from application =C-c g=]]
  - [[#custom-functions][Custom functions]]
    - [[#insert-date][Insert date]]
    - [[#insert-a-timestamp][Insert a timestamp]]
    - [[#insert-custom-clock-entry-c-][Insert custom clock entry =C-'=]]
    - [[#insert-clipboard-image-c-m-y][Insert clipboard image =C-M-y=]]
    - [[#remove-all-results-from-an-org-document-s-][Remove all results from an org document =s-]=]]
  - [[#custom-keybindings][Custom keybindings]]
    - [[#open-files-from-the-bookmarks-list][Open files from the bookmarks list]]
- [[#visual-settings][Visual settings]]
  - [[#maximize-emacs-frame-on-startup][Maximize Emacs frame on startup]]
  - [[#theme][Theme]]
  - [[#fonts-and-icons][Fonts and Icons]]
    - [[#default-font][Default font]]
    - [[#variable-pitch][Variable pitch]]
    - [[#big-font][Big font]]
    - [[#enable-bolditalic-fonts][Enable bold/italic fonts]]
  - [[#set-custom-faces][Set custom faces]]
  - [[#line-settings][Line settings]]
    - [[#enable-line-numbers][Enable line numbers]]
    - [[#toggle-truncate-lines][Toggle Truncate lines]]
  - [[#mode-line-settings][Mode Line settings]]
    - [[#enable-the-display-of-time-and-date-in-the-mode-line][Enable the display of time and date in the mode line]]
    - [[#limit-mode-line-vcs-length][Limit mode line vcs length]]
- [[#package-configuration][Package configuration]]
  - [[#auto-dim-other-buffers][Auto dim other buffers]]
  - [[#deft][Deft]]
  - [[#dired][Dired]]
    - [[#enable-dual-pane][Enable dual pane]]
  - [[#forge][Forge]]
  - [[#magit][Magit]]
  - [[#ob-mermaid][Ob-mermaid]]
  - [[#org-mode][Org mode]]
    - [[#set-the-org-base-directory][Set the org base directory]]
    - [[#org-general-settings][Org general settings]]
    - [[#org-custom-functions][Org custom functions]]
    - [[#org-agenda][Org agenda]]
    - [[#org-calendar][Org calendar]]
    - [[#org-capture-templates][Org capture templates]]
    - [[#org-babel][Org babel]]
    - [[#org-bullets][Org bullets]]
    - [[#org-journal][Org journal]]
    - [[#org-roam][Org roam]]
  - [[#zoom-window][Zoom window]]
  - [[#smartparens][Smartparens]]
- [[#general-programming][General Programming]]
  - [[#css][CSS]]
  - [[#json][JSON]]
    - [[#c-c-c-f-json-beautify][=C-c C-f= Json beautify]]
  - [[#markdown][Markdown]]
- [[#programming][Programming]]
  - [[#cider][Cider]]
  - [[#clojure][Clojure]]

* References
** Config file headers
#+html: <details><summary>config.el</summary>
#+begin_src emacs-lisp :tangle config.el
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
;; (setq user-full-name "John Doe"
;;      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
;; (setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
;; (setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
;; (setq display-line-numbers-type t)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src
#+html: </details>

** Customized variables

Doom [[https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#configure][does not recommend the Emacs =customize= mechanism]]:

#+begin_quote
/Note: do not use M-x customize or the customize API in general. Doom is designed to be configured programmatically from your config.el, which can conflict with Customize’s way of modifying variables./
#+end_quote

All necessary settings are therefore set by hand as part of this configuration file. The only exceptions are "safe variable" and "safe theme" settings, which are automatically saved by Emacs in =custom.el=, but this is OK as they don't conflict with anything else from the config.

* Global constants
** Directories

Base directories that are used for org/roam/deft

#+begin_src emacs-lisp
(setq my/home-dir "~")
(setq my/org-base-dir (concat my/home-dir "/Dropbox/notes/org/"))
#+end_src

* Personal Information

Let's set some variables with basic user information.

** Set full name
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Marco Pas")
#+END_SRC

** Set email address

#+BEGIN_SRC emacs-lisp
(setq user-mail-address "marco.pasopas@gmail.com")
#+END_SRC

* General configuration
** Set the authentication source to use

#+begin_src emacs-lisp
(setq auth-sources '("~/.authinfo"))
#+end_src

** Disable exit confirmation

#+begin_src emacs-lisp
(setq confirm-kill-emacs nil)
#+end_src

** Keybindings
*** Remove entire line when at the beginning =C-k=
When at the beginning of the line, make =Ctrl-K= remove the whole line, instead of just emptying it.

#+begin_src emacs-lisp
(setq kill-whole-line t)
#+end_src

*** Closes the current buffer =C=

Close the current buffer mapped to 'c' in normal mode.

#+begin_src emacs-lisp
(map! :map evil-normal-state-map
      :desc "Close the current buffer"
      :ng "c" #'kill-this-buffer)
#+end_src

*** Cycle through the open windows =C-w C-w=

#+begin_src emacs-lisp
(map! :map evil-normal-state-map
      :desc "Cycle through windows"
      :ng "C-w C-w" #'evil-window-next)
#+end_src

*** Grab open link from application =C-c g=

Shortcut to grab a link from an open Mac application.

#+begin_src emacs-lisp
(add-hook 'org-mode-hook (lambda ()
                           (define-key org-mode-map (kbd "C-c g") 'org-mac-grab-link)))
#+end_src


** Custom functions

*** Insert date

#+begin_src emacs-lisp
(defun insert-date (arg)
  (interactive "P")
  (insert (if arg
              (format-time-string "%d.%m.%Y")
            (format-time-string "%Y-%m-%d"))))
#+end_src

*** Insert a timestamp

#+begin_src emacs-lisp
(defun insert-timestamp ()
  (interactive)
  (insert (format-time-string "%Y-%m-%dT%H:%M:%S")))
#+end_src

*** Insert custom clock entry =C-'=

#+begin_src emacs-lisp
(defun jx/insert-custom-clock-entry ()
  (interactive)
  (insert "CLOCK: ")
  (org-time-stamp-inactive)
  (insert "--")
  ;; Inserts the current time by default.
  (let ((current-prefix-arg '(4))) (call-interactively 'org-time-stamp-inactive))
  (org-ctrl-c-ctrl-c))

                                        ; Shortcut
(define-key evil-normal-state-map (kbd "C-'") 'jx/insert-custom-clock-entry)
(define-key evil-insert-state-map (kbd "C-'") 'jx/insert-custom-clock-entry)
#+end_src

*** Insert clipboard image =C-M-y=

Use the current headername as part of the image filename
#+begin_src emacs-lisp
(setq my/insert-clipboard-image-use-headername t)
#+end_src

Use the current buffername as part of the screenshot filename
#+begin_src emacs-lisp
(setq my/insert-clipboard-image-use-buffername t)
#+end_src

Function that allows a screenshot to be pasted in a Org-mode file. The relative link will be pasted into the document and a relative =./images= will be created to store the images.

#+begin_src emacs-lisp
;; Overview
;; --------
;; Inserts an image from the clipboard by prompting the user for a filename.
;; Default extension for the pasted filename is .png

;; A ./images directory will be created relative to the current Org-mode document to store the images.

;; The default name format of the pasted image is:
;; filename: <yyyymmdd>_<hhmmss>_-_<image-filename>.png

;; Important
;; --------
;; This function depends on 'pngpaste' to paste the clipboard image
;; -> $ brew install pngpaste

;; Basic Customization
;; -------------------
;; Include the current Org-mode header as part of the image name.
;; (setq my/insert-clipboard-image-use-headername t)
;; filename: <yyyymmdd>_<hhmmss>_-_<headername>_-_<image-filename>.png

;; Include the buffername as part of the image name.
;; (setq my/insert-clipboard-image-use-buffername t)
;; filename: <yyyymmdd>_<hhmmss>_-_<buffername>_-_<image-filename>.png

;; Full name format
;; filename: <yyyymmdd>_<hhmmss>_-_<buffername>_-_<headername>_-_<image-filename>.png
(defun my/insert-clipboard-image (filename)
  "Inserts an image from the clipboard"
  (interactive "sFilename to paste: ")
  (let ((file
         (concat
          (file-name-directory buffer-file-name)
          "images/"
          (format-time-string "%Y%m%d_%H%M%S_-_")
          (if (bound-and-true-p my/insert-clipboard-image-use-buffername)
              (concat (s-replace "-" "_"
                                 (downcase (file-name-sans-extension (buffer-name)))) "_-_")
            "")
          (if (bound-and-true-p my/insert-clipboard-image-use-headername)
              (concat (s-replace " " "_" (downcase (nth 4 (org-heading-components)))) "_-_")
            "")
          filename ".png")))

    ;; create images directory
    (unless (file-exists-p (file-name-directory file))
      (make-directory (file-name-directory file)))

    ;; paste file from clipboard
    (shell-command (concat "pngpaste " file))
    (insert (concat "[[./images/" (file-name-nondirectory file) "]]"))))
#+end_src

Bind insert clipboard image to Ctrl-Option-y

#+begin_src emacs-lisp
(map! :desc "Insert clipboard image"
      :n "C-M-y" 'my/insert-clipboard-image)
#+end_src

*** Remove all results from an org document =s-]=
#+begin_src emacs-lisp
(defconst help/org-special-pre "^\s*#[+]")
(defun help/org-2every-src-block (fn)
  "Visit every Source-Block and evaluate `FN'."
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (let ((case-fold-search t))
      (while (re-search-forward (concat help/org-special-pre "BEGIN_SRC") nil t)
        (let ((element (org-element-at-point)))
          (when (eq (org-element-type element) 'src-block)
            (funcall fn element)))))
    (save-buffer)))

(after! org
   (define-key org-mode-map (kbd "s-]") (lambda () (interactive)
                                       (help/org-2every-src-block
                                        'org-babel-remove-result))))
#+end_src

** Custom keybindings
*** Open files from the bookmarks list
#+begin_src emacs-lisp
(map! :desc "Open bookmarks list"
      :n "C-c b" 'list-bookmarks)
#+end_src

* Visual settings
** Maximize Emacs frame on startup

#+begin_src emacs-lisp
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
#+end_src

** Theme

Sets the default theme

#+begin_src emacs-lisp
(setq doom-theme 'doom-vibrant)
(setq doom-vibrant-brighter-comments t  ;; "If non-nil, more vivid colors will be used to style the mode-line."
      doom-vibrant-brighter-modeline t  ;; "If non-nil, comments will be highlighted in more vivid colors."
      doom-vibrant-comment-bg t)        ;; "If non-nil, comments will have a subtle, darker background. Enhancing their legibility."
#+end_src
** Fonts and Icons
*** Default font

doom-font is the default font for emacs to use

#+begin_src emacs-lisp
;; (setq doom-font (font-spec :family "FiraCode Nerd Font Mono" :size 16))
#+end_src

*** Variable pitch

doom-variable-pitch-font is a proportional font used for reading emails, doc etc.

#+begin_src emacs-lisp
;; (setq doom-variable-pitch-font (font-spec :family "Ubuntu" :size 14))
#+end_src

*** Big font

doom-big-font is the default font to use for doom-big-font-mode

#+begin_src emacs-lisp
;; (setq doom-big-font (font-spec :family "FiraCode Nerd Font Mono" :size 30))
#+end_src

*** Enable bold/italic fonts

#+begin_src emacs-lisp
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
#+end_src

** Set custom faces

#+begin_src emacs-lisp
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+end_src

** Line settings
I have toggled display-line-numbers-type so I have line numbers displayed.  Doom Emacs uses 'SPC t' for "toggle" commands, so I choose 'SPC t t' for toggle-truncate-lines.

*** Enable line numbers

#+begin_src emacs-lisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)
#+end_src

*** Toggle Truncate lines

#+begin_src emacs-lisp
(map! :leader
      :desc "Toggle truncate lines"
      "t t" #'toggle-truncate-lines)
#+end_src

** Mode Line settings
*** Enable the display of time and date in the mode line

#+begin_src emacs-lisp
(display-time-mode 1)
(setq display-time-day-and-date t)
#+end_src

*** Limit mode line vcs length

#+begin_src emacs-lisp
(setq doom-modeline-vcs-max-length 80)
#+end_src

#+begin_src emacs-lisp
(after! doom-modeline
  (setq doom-modeline-bar-width 3))
#+end_src
* Package configuration
** Auto dim other buffers

The auto-dim-other-buffers-mode is a global minor mode which makes windows without focus less prominent. With many windows in a frame, the idea is that this mode helps recognise which is the selected window by providing a non-intrusive but still noticeable visual indicator.

#+begin_src emacs-lisp
(add-hook 'after-init-hook (lambda ()
  (when (fboundp 'auto-dim-other-buffers-mode)
    (auto-dim-other-buffers-mode t))))
#+end_src

** Deft

#+begin_src emacs-lisp
(setq deft-directory my/org-base-dir
      deft-default-extension "org"
      deft-extensions '("txt" "md" "org")
      deft-recursive t
      deft-use-filename-as-title t
      deft-use-filter-string-for-filename t
      deft-file-naming-rules '((noslash . "-")
                               (nospace . "-")
                               (case-fn . downcase)))
#+end_src

** Dired

*** Enable dual pane

Enable Dired to use a dual pane layout. If non-nil, Dired tries to guess a default target directory. This means: if there is a Dired buffer displayed in the next window, use its current directory, instead of this Dired buffer's current directory.

Go to dired, split your window, split-window-vertically & go to another dired directory. When you will press C to copy, the other dir in the split pane will be default destination.

#+begin_src emacs-lisp
(setq dired-dwim-target t)
#+end_src

** Forge

#+begin_src emacs-lisp
;; Configure number of topics show, open and closed
;; use negative number to toggle the view of closed topics
;; using `forge-toggle-closed-visibility'
(setq  forge-topic-list-limit '(100 . -10))

;; set closed to 0 to never show closed issues
;; (setq  forge-topic-list-limit '(100 . 0))
#+end_src

** Magit

Functions to open links to the files in a Git Repo. This is shameless taken from [[https://gist.github.com/dotemacs/9a0433341e75e01461c9][GitHub Gist]] and [[https://github.com/arthurcgusmao/acg-emacs/commit/2257058e424b82e1d670cadf2e870f0a6a37d669][ACG Emacs]]

#+begin_src emacs-lisp
(defun acg/parse-git-remote-url (url)
  "If necessary, convert an SSH to HTTPS git remote location."
  (if (string-match "^http" url)
      url
    (replace-regexp-in-string "\\(.*\\)@\\(.*\\):\\(.*\\)\\(\\.git?\\)"
                              "https://\\2/\\3"
                              url)))

(defun acg/magit-open-remote-repo ()
  "Opens a remote repo URL. Prompts the user to choose a remote."
  (interactive)
  (let* ((remote-name (magit-read-remote "Choose remote repository"))
         (url (magit-get "remote" remote-name "url")))
    (browse-url (acg/parse-git-remote-url url))
    (message "Opening repo %s" url)))

(defun acg/project-get-root-relative-path (&optional path)
  "Returns PATH relative to a project root."
  (let* ((path (expand-file-name (or path default-directory)))
         (root-path (expand-file-name
                     (cdr (project--find-in-directory path))))
         (root-length (length root-path))
         (rel-path (substring path root-length)))
    rel-path))

(defun acg/magit-open-remote-dwim (&optional dir)
  "Opens a remote repo URL in the exact DIR location. Prompts the user to choose a remote."
  (interactive)
  (let* ((file (buffer-file-name))
         (dir (expand-file-name (or dir default-directory)))
         (remote-name (magit-read-remote "Choose remote repository" nil t))
         (url (acg/parse-git-remote-url
               (magit-get "remote" remote-name "url")))
         ;; Identify remote hosting type (e.g., GitHub, GitLab, etc.)
         (remote-hosting-type
          (cond
           ((string-match-p (regexp-quote "github") url) "GitHub")
           ((string-match-p (regexp-quote "gitlab") url) "GitLab")
           (t (completing-read "Choose remote hosting type:"
                               '("GitHub" "GitLab"))))))
    ;; Adapt to GitLab's URL standard
    (when (string= remote-hosting-type "GitLab")
      (setq url (concat url "/-")))
    ;; Adapt to differences in file and directory URL paths
    (if file
        (setq url (concat url "/blob/" (magit-get-current-branch)
                          "/" (acg/project-get-root-relative-path file)))
      (setq url (concat url "/tree/" (magit-get-current-branch)
                        "/" (acg/project-get-root-relative-path dir))))
    ;; Perform actions
    (browse-url url)
    (message "Opening %s" url)))
#+end_src

** Ob-mermaid

[[https://mermaid-js.github.io/][Mermaid]] lets you create diagrams using text and code. [[https://github.com/arnm/ob-mermaid][Ob-mermaid]] enables the use of this inside Org-mode.

Set the path to the Mermaid CLI, this has been installed using =brew install mermaid-cli== but the executable is named mmdc.
#+begin_src emacs-lisp
(setq ob-mermaid-cli-path "/usr/local/bin/mmdc")
#+end_src

** Org mode

*** Set the org base directory

Set base directory where org mode can find the org files

If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!

#+begin_src emacs-lisp
(setq org-directory my/org-base-dir)
#+end_src

*** Org general settings

Hide the markers (*,_, ...) when making text bold/italic etc

#+begin_src emacs-lisp
(setq org-hide-emphasis-markers t)
#+end_src

<<org-duration-format>>Set the output of the duration format to =hours:min= so we can sum these later on in org tables. The default format when passing 24 hours is 1d .. As we need to sum the duration we need the actual hours.

#+begin_src emacs-lisp
(setq org-duration-format 'h:mm)
#+end_src

Use Org Log =done= to auto insert a 'CLOSED' property when changing state below the heading. This is used for =ox-hugo= that ox-hugo auto-sets the date field in the front-matter to the time stamp in that CLOSED property. For more information see [[https://ox-hugo.scripter.co/doc/org-capture-setup/][Org Hugo capture setup]].

#+begin_src emacs-lisp
(setq org-log-done 'time)
#+end_src

Set default todo/tasks states

#+begin_src emacs-lisp
(after! org
  (setq org-todo-keywords
      '((sequence "TODO" "DOING" "BLOCKED" "|" "DONE" "ARCHIVED"))))
#+end_src

Set the refile targets

#+begin_src emacs-lisp
  (setq org-refile-targets '((org-agenda-files :maxlevel . 9)))
#+end_src

With (setq org-tags-match-list-sublevels 'indented), a number of dots equal to the level will be prepended to each agenda line to indicate its level.

#+begin_src emacs-lisp
(after! org
  (setq org-tags-match-list-sublevels 'indented))
#+end_src

Set the location of the tags, use =SPC-u C-c C-c= to re-align of needed.

#+begin_src emacs-lisp
(after! org
  (setq org-tags-column -120))
#+end_src

Remove category display for todo items

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-prefix-format
        '((agenda . " %i %-12:c%?-12t% s")
          (todo   . " ")
          (tags   . " %i %-12:c")
          (search . " %i %-12:c"))))
#+end_src

Set the size of images shown in org mode

#+begin_src emacs-lisp
(after! org
  (setq org-image-actual-width (/ (display-pixel-width) 2)))
#+end_src

*** Org custom functions

**** Return a list of files that have clockable items

#+begin_src emacs-lisp
(defun clockable-files ()
  "Returns org files that contain clockable items"
  (directory-files-recursively (concat my/org-base-dir "journal/") ".org"))
#+end_src

**** Function to change the format of a duration to HH:MM

This function can be applied to a table. Using a =#+TBLFMT:=. I am using this function to enable [[https://github.com/tbanel/orgaggregate][Org Aggregate]] time duration sums. The expected format for the time durations is =HH:MM=.

Also check the correct setting for [[org-duration-format][org-duration-format]]

#+BEGIN_EXAMPLE
;; Convert the time strings in column $3 and place them in column $5, also set the header of column $5
#+TBLFM: $5='(convert-org-clocktable-time-to-hhmm $3)::@1$5='(format "%s" "T")
#+END_EXAMPLE

#+begin_src emacs-lisp
(defun convert-org-clocktable-time-to-hhmm (time-string)
  "Converts a time string to HH:MM"
  (if (> (length time-string) 0)
      (progn
        (let* ((s (s-replace "*" "" time-string))
               (splits (split-string s ":"))
               (hours (car splits))
               (minutes (car (last splits)))
               )
          (if (= (length hours) 1)
              (format "0%s:%s" hours minutes)
            (format "%s:%s" hours minutes))))
    time-string))
#+end_src

*** Org agenda

Hide tags in the org-agenda todo list

#+begin_src emacs-lisp
  (setq org-agenda-hide-tags-regexp ".")
#+end_src

Set the files that are used to fill org agenda

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-files
        (append (list (concat my/org-base-dir "inbox.org")
                      (concat my/org-base-dir "agenda.org"))
                (directory-files-recursively (concat my/org-base-dir "journal/")  "\\.org$"))))
#+end_src

Set the time span for the agenda overview

#+begin_src emacs-lisp
;; (setq org-agenda-start-day -2)
;; (setq org-agenda-span 3)
;; (setq org-agenda-start-day "+3d")
#+end_src

*** Org calendar

#+begin_src emacs-lisp
(after! org
  (setq calendar-week-start-day 1)
  (setq calendar-intermonth-text
        '(propertize
          (format "%2d"
                  (car
                   (calendar-iso-from-absolute
                    (calendar-absolute-from-gregorian (list month day year)))))
          'font-lock-face 'font-lock-warning-face))
  (setq calendar-intermonth-header
        (propertize "Wk"                  ; or e.g. "KW" in Germany
                    'font-lock-face 'font-lock-keyword-face)))
#+end_src

*** Org capture templates

Function that returns a Hugo post capture template.

#+begin_src emacs-lisp
(defun org-hugo-new-subtree-post-capture-template ()
  "Returns `org-capture' template string for new Hugo post.
   See `org-capture-templates' for more information."
  (let* ((title (read-from-minibuffer "Post Title: ")) ;Prompt to enter the post title
         (fname (org-hugo-slug title)))
    (mapconcat #'identity
               `(
                 ,(concat "* TODO " title)
                 ":PROPERTIES:"
                 ,(concat ":EXPORT_FILE_NAME: " fname)
                 ":END:"
                 "%?\n")          ;Place the cursor here finally
               "\n")))
#+end_src

Set the to be be used capture templates!

#+begin_src emacs-lisp
(after! org
  ;; clean the intial existing template list
  (setq org-capture-templates '())


  ;; add inbox capture template
  (add-to-list 'org-capture-templates
               `("i" "Inbox" entry (file+headline "inbox.org" "Inbox")
                 ,(concat "** TODO %?\n"
                          "/Entered on/ %U")))

  ;; add meeting capture template
  (add-to-list 'org-capture-templates
               `("m" "Meeting" entry (file+headline "agenda.org" "Planned")
                 ,(concat "* %? :meeting:\n"
                          "<%<%Y-%m-%d %a %H:00>>")))

  ;; add hugo capture template
  (add-to-list 'org-capture-templates
               '("h"                ;`org-capture' binding + h
                 "Hugo post"
                 entry
                 ;; It is assumed that below file is present in `org-directory'
                 ;; and that it has a "Blog Ideas" heading. It can even be a
                 ;; symlink pointing to the actual location of all-posts.org!
                 (file+olp "~/Dropbox/notes/org/blog/blog.org" "Posts")
                 (function org-hugo-new-subtree-post-capture-template) :prepend t)))
#+end_src

#+RESULTS:
| h | Hugo post | entry | (file+olp ~/Dropbox/notes/org/blog/blog.org Posts) | #'org-hugo-new-subtree-post-capture-template | :prepend | t |
| m | Meeting   | entry | (file+headline agenda.org Planned)                 | * %? :meeting:                               |          |   |

*** Org babel

#+begin_src emacs-lisp
(setq org-babel-clojure-backend 'cider)
#+end_src

#+begin_src emacs-lisp
(after! 'org
            (org-babel-do-load-languages 'org-babel-load-languages
                                         (append org-babel-load-languages
                                                 ;; '((julia . t))
                                                 '((gnuplot . t))
                                                 ))
            )
;; (!after org
;;         (org-babel-do-load-languages
;;          'org-babel-load-languages
;;          '(
;;            (python     . t)
;;            (ruby       . t)
;;            (calc       . t)
;;            (ditaa      . t)
;;            (dot        . t)
;;            (emacs-lisp . t)
;;            (gnuplot    . t)
;;            (latex      . t)
;;            (plantuml   . t)
;;            (python     . t)
;;            (ruby       . t)
;;            (shell      . t)
;;            (sqlite     . t)
;;            (sql        . t))))
#+end_src

*** Org bullets

Make sure we have nice bullets for org headings.
#+begin_src emacs-lisp
(setq org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿"))
#+end_src

*** Org journal

Set the location of the journal files.

#+begin_src emacs-lisp
(setq org-journal-dir (concat my/org-base-dir "journal"))
#+end_src

A better title for a journal entry, instead of using a top header with the date, we use the TITLE meta field.

#+begin_src emacs-lisp
(setq org-journal-date-prefix "#+TITLE: ")
#+end_src

Normally the hours level is a second level heading, change that to first level.

#+begin_src emacs-lisp
(setq org-journal-time-prefix "* ")
#+end_src

Use a better date format: day, year-month-day.

#+begin_src emacs-lisp
(setq org-journal-date-format "%a, %Y-%m-%d")
#+end_src

Set a good format for the journal file e.g. year-month-day with a .org extensions.

#+begin_src emacs-lisp
(setq org-journal-file-format "%Y-%m-%d.org")
#+end_src

Enable integration with org-agenda so we can view the entries.

#+begin_src emacs-lisp
(setq org-journal-enable-agenda-integration t)
#+end_src

# Set default tags to be used for journal entries

#+begin_src emacs-lisp
(setq org-journal-tag-persistent-alist '(
                                         ("@work" . ?w)
                                         ("@private" . ?p)
                                         ("fontys" . ?f)
                                         ("ctoprogram" . ?c)
                                         ("integrationlab" . ?i)
                                         ("swat" . ?s)
                                         ("interruption" . ?!)
                                         ("various" . ?v)
                                         ))
#+end_src

*** Org roam

Set the default path to Org-roam files.

#+begin_src emacs-lisp
(setq org-roam-directory (concat my/org-base-dir "roam"))
#+end_src

If non-nil, open the org-roam buffer when opening an org roam file. I set it to nil so the roam buffer will not show every time i open a org file.

#+begin_src emacs-lisp
(setq +org-roam-open-buffer-on-find-file nil)
#+end_src

** Zoom window

Make it possible to zoom in/out the current window.

#+begin_src emacs-lisp
;; https://github.com/emacsorphanage/zoom-window
(custom-set-variables
 '(zoom-window-mode-line-color "purple"))
(map! :desc "Zoom/Unzoom the current window"
      :n "C-w z" 'zoom-window-zoom)
#+end_src

** Smartparens

Smartparens is a minor mode for dealing with pairs in Emacs.

#+begin_src emacs-lisp
(after! smartparens
  (add-hook! (clojure-mode emacs-lisp-mode lisp-mode cider-repl-mode) :append #'smartparens-strict-mode))
(map!
 :map smartparens-mode-map
 ;; smartparens maps (navigation ops)
 :nvie "C-M-f" #'sp-forward-sexp
 :nvie "C-M-b" #'sp-backward-sexp
 :nvie "C-M-u" #'sp-backward-up-sexp
 :nvie "C-M-d" #'sp-down-sexp
 ;; smartparens maps (split join slurp barf)
 :nie "M-s" #'sp-split-sexp
 :nie "M-j" #'sp-join-sexp
 :nvie "C->" #'sp-forward-slurp-sexp
 :nvie "C-<" #'sp-forward-barf-sexp
 :nvie "C-{" #'sp-backward-slurp-sexp
 :nvie "C-}" #'sp-backward-barf-sexp)
#+end_src

* General Programming
** CSS
Set default indentation for css to 2 spaces

#+begin_src emacs-lisp
(after! css-mode
  (setq css-indent-offset 2))
#+end_src
** JSON
Lets format JSON with a specific width

#+begin_src emacs-lisp
(setq json-reformat:indent-width 2)
#+end_src

*** =C-c C-f= Json beautify

#+begin_src emacs-lisp
(map! :desc "JSON beautify"
      :n "C-c C-f" 'json-mode-beautify)
#+end_src

** Markdown
#+begin_src emacs-lisp
(map! :localleader
      :map markdown-mode-map
      :prefix ("i" . "Insert")
      :desc "Blockquote"    "q" 'markdown-insert-blockquote
      :desc "Bold"          "b" 'markdown-insert-bold
      :desc "Code"          "c" 'markdown-insert-code
      :desc "Emphasis"      "e" 'markdown-insert-italic
      :desc "Footnote"      "f" 'markdown-insert-footnote
      :desc "Code Block"    "s" 'markdown-insert-gfm-code-block
      :desc "Image"         "i" 'markdown-insert-image
      :desc "Link"          "l" 'markdown-insert-link
      :desc "List Item"     "n" 'markdown-insert-list-item
      :desc "Pre"           "p" 'markdown-insert-pre
      (:prefix ("h" . "Headings")
        :desc "One"   "1" 'markdown-insert-header-atx-1
        :desc "Two"   "2" 'markdown-insert-header-atx-2
        :desc "Three" "3" 'markdown-insert-header-atx-3
        :desc "Four"  "4" 'markdown-insert-header-atx-4
        :desc "Five"  "5" 'markdown-insert-header-atx-5
        :desc "Six"   "6" 'markdown-insert-header-atx-6))
#+end_src

* Programming
** Cider
Make the Cider popup window appear in the right hand side.

#+begin_src emacs-lisp
(after! cider
  (set-popup-rule! "^\\*cider-repl" :side 'right :size 0.3 :quit nil :ttl 0))
#+end_src

** Clojure
