#+TITLE: Doom Emacs configuration
#+AUTHOR: Marco Pas
#+EMAIL: marco.pasopas@gmail.com
#+EXPORT_FILE_NAME: README.md
#+PROPERTY: header-args:emacs-lisp :tangle config.el
#+STARTUP: fold

* Table of Contents :TOC_3:noexport:
- [[#references][References]]
  - [[#config-file-headers][Config file headers]]
  - [[#customized-variables][Customized variables]]
- [[#global-constants][Global constants]]
  - [[#directories][Directories]]
- [[#personal-information][Personal Information]]
  - [[#set-full-name][Set full name]]
  - [[#set-email-address][Set email address]]
- [[#general-configuration][General configuration]]
  - [[#set-the-authentication-source-to-use][Set the authentication source to use]]
  - [[#disable-exit-confirmation][Disable exit confirmation]]
  - [[#keybindings][Keybindings]]
    - [[#remove-entire-line-when-at-the-beginning-c-k][Remove entire line when at the beginning =C-k=]]
    - [[#closes-the-current-buffer-c][Closes the current buffer =C=]]
    - [[#cycle-through-the-open-windows-c-w-c-w][Cycle through the open windows =C-w C-w=]]
  - [[#custom-functions][Custom functions]]
    - [[#insert-date][Insert date]]
    - [[#insert-a-timestamp][Insert a timestamp]]
- [[#visual-settings][Visual settings]]
  - [[#maximize-emacs-frame-on-startup][Maximize Emacs frame on startup]]
  - [[#theme][Theme]]
  - [[#fonts-and-icons][Fonts and Icons]]
    - [[#default-font][Default font]]
    - [[#variable-pitch][Variable pitch]]
    - [[#big-font][Big font]]
    - [[#enable-bolditalic-fonts][Enable bold/italic fonts]]
  - [[#set-custom-faces][Set custom faces]]
  - [[#line-settings][Line settings]]
    - [[#enable-line-numbers][Enable line numbers]]
    - [[#toggle-truncate-lines][Toggle Truncate lines]]
  - [[#mode-line-settings][Mode Line settings]]
    - [[#enable-the-display-of-time-and-date-in-the-mode-line][Enable the display of time and date in the mode line]]
    - [[#limit-mode-line-vcs-length][Limit mode line vcs length]]
- [[#package-configuration][Package configuration]]
  - [[#auto-dim-other-buffers][Auto dim other buffers]]
  - [[#deft][Deft]]
  - [[#dired][Dired]]
    - [[#enable-dual-pane][Enable dual pane]]
  - [[#forge][Forge]]
  - [[#org-mode][Org mode]]
    - [[#set-the-org-base-directory][Set the org base directory]]
    - [[#org-general-settings][Org general settings]]
    - [[#org-custom-functions][Org custom functions]]
    - [[#org-agenda][Org agenda]]
    - [[#org-calendar][Org calendar]]
    - [[#org-capture-templates][Org capture templates]]
    - [[#org-babel][Org babel]]
    - [[#org-bullets][Org bullets]]
    - [[#org-journal][Org journal]]
    - [[#org-roam][Org roam]]
  - [[#zoom-window][Zoom window]]
  - [[#smartparens][Smartparens]]
- [[#general-programming][General Programming]]
  - [[#css][CSS]]
  - [[#json][JSON]]
    - [[#c-c-c-f-json-beautify][=C-c C-f= Json beautify]]
  - [[#markdown][Markdown]]
- [[#programming][Programming]]
  - [[#cider][Cider]]
  - [[#clojure][Clojure]]

* References
** Config file headers
#+html: <details><summary>config.el</summary>
#+begin_src emacs-lisp :tangle config.el
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
;; (setq user-full-name "John Doe"
;;      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
;; (setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
;; (setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
;; (setq display-line-numbers-type t)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src
#+html: </details>

** Customized variables

Doom [[https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#configure][does not recommend the Emacs =customize= mechanism]]:

#+begin_quote
/Note: do not use M-x customize or the customize API in general. Doom is designed to be configured programmatically from your config.el, which can conflict with Customize’s way of modifying variables./
#+end_quote

All necessary settings are therefore set by hand as part of this configuration file. The only exceptions are "safe variable" and "safe theme" settings, which are automatically saved by Emacs in =custom.el=, but this is OK as they don't conflict with anything else from the config.

* Global constants
** Directories

Base directories that are used for org/roam/deft

#+begin_src emacs-lisp
(setq my/home-dir "~")
(setq my/org-base-dir (concat my/home-dir "/Dropbox/notes/org/"))
#+end_src

* Personal Information

Let's set some variables with basic user information.

** Set full name
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Marco Pas")
#+END_SRC

** Set email address

#+BEGIN_SRC emacs-lisp
(setq user-mail-address "marco.pasopas@gmail.com")
#+END_SRC

* General configuration
** Set the authentication source to use

#+begin_src emacs-lisp
(setq auth-sources '("~/.authinfo"))
#+end_src

** Disable exit confirmation

#+begin_src emacs-lisp
(setq confirm-kill-emacs nil)
#+end_src

** Keybindings
*** Remove entire line when at the beginning =C-k=
When at the beginning of the line, make =Ctrl-K= remove the whole line, instead of just emptying it.

#+begin_src emacs-lisp
(setq kill-whole-line t)
#+end_src

*** Closes the current buffer =C=

Close the current buffer mapped to 'c' in normal mode.

#+begin_src emacs-lisp
(map! :map evil-normal-state-map
      :desc "Close the current buffer"
      :ng "c" #'kill-this-buffer)
#+end_src

*** Cycle through the open windows =C-w C-w=

#+begin_src emacs-lisp
(map! :map evil-normal-state-map
      :desc "Cycle through windows"
      :ng "C-w C-w" #'evil-window-next)
#+end_src

** Custom functions

*** Insert date

#+begin_src emacs-lisp
(defun insert-date (arg)
  (interactive "P")
  (insert (if arg
              (format-time-string "%d.%m.%Y")
            (format-time-string "%Y-%m-%d"))))
#+end_src

*** Insert a timestamp

#+begin_src emacs-lisp
(defun insert-timestamp ()
  (interactive)
  (insert (format-time-string "%Y-%m-%dT%H:%M:%S")))
#+end_src

* Visual settings
** Maximize Emacs frame on startup

#+begin_src emacs-lisp
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
#+end_src

** Theme

Sets the default theme

#+begin_src emacs-lisp
(setq doom-theme 'doom-vibrant)
(setq doom-vibrant-brighter-comments t  ;; "If non-nil, more vivid colors will be used to style the mode-line."
      doom-vibrant-brighter-modeline t  ;; "If non-nil, comments will be highlighted in more vivid colors."
      doom-vibrant-comment-bg t)        ;; "If non-nil, comments will have a subtle, darker background. Enhancing their legibility."
#+end_src
** Fonts and Icons
*** Default font

doom-font is the default font for emacs to use

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "FiraCode Nerd Font Mono" :size 16))
#+end_src

*** Variable pitch

doom-variable-pitch-font is a proportional font used for reading emails, doc etc.

#+begin_src emacs-lisp
(setq doom-variable-pitch-font (font-spec :family "Ubuntu" :size 14))
#+end_src

*** Big font

doom-big-font is the default font to use for doom-big-font-mode

#+begin_src emacs-lisp
(setq doom-big-font (font-spec :family "FiraCode Nerd Font Mono" :size 30))
#+end_src

*** Enable bold/italic fonts

#+begin_src emacs-lisp
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
#+end_src

** Set custom faces

#+begin_src emacs-lisp
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+end_src

** Line settings
I have toggled display-line-numbers-type so I have line numbers displayed.  Doom Emacs uses 'SPC t' for "toggle" commands, so I choose 'SPC t t' for toggle-truncate-lines.

*** Enable line numbers

#+begin_src emacs-lisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)
#+end_src

*** Toggle Truncate lines

#+begin_src emacs-lisp
(map! :leader
      :desc "Toggle truncate lines"
      "t t" #'toggle-truncate-lines)
#+end_src

** Mode Line settings
*** Enable the display of time and date in the mode line

#+begin_src emacs-lisp
(display-time-mode 1)
(setq display-time-day-and-date t)
#+end_src

*** Limit mode line vcs length

#+begin_src emacs-lisp
(setq doom-modeline-vcs-max-length 80)
#+end_src

#+begin_src emacs-lisp
(after! doom-modeline
  (setq doom-modeline-bar-width 3))
#+end_src
* Package configuration
** Auto dim other buffers

The auto-dim-other-buffers-mode is a global minor mode which makes windows without focus less prominent. With many windows in a frame, the idea is that this mode helps recognise which is the selected window by providing a non-intrusive but still noticeable visual indicator.

#+begin_src emacs-lisp
(add-hook 'after-init-hook (lambda ()
  (when (fboundp 'auto-dim-other-buffers-mode)
    (auto-dim-other-buffers-mode t))))
#+end_src

** Deft

#+begin_src emacs-lisp
(setq deft-directory my/org-base-dir
      deft-default-extension "org"
      deft-extensions '("txt" "md" "org")
      deft-recursive t
      deft-use-filename-as-title t
      deft-use-filter-string-for-filename t
      deft-file-naming-rules '((noslash . "-")
                               (nospace . "-")
                               (case-fn . downcase)))
#+end_src

** Dired

*** Enable dual pane

Enable Dired to use a dual pane layout. If non-nil, Dired tries to guess a default target directory. This means: if there is a Dired buffer displayed in the next window, use its current directory, instead of this Dired buffer's current directory.

Go to dired, split your window, split-window-vertically & go to another dired directory. When you will press C to copy, the other dir in the split pane will be default destination.

#+begin_src emacs-lisp
(setq dired-dwim-target t)
#+end_src

** Forge

#+begin_src emacs-lisp
(with-eval-after-load 'forge
  (setq forge-topic-list-columns
      '(("#" 5 t (:right-align t) number nil)
        ("Title" 60 t nil title  nil)
        ("State" 6 t nil state nil)
        ("Marks" 8 t nil marks nil)
        ("Labels" 8 t nil labels nil)
        ("Assignees" 10 t nil assignees nil)
        ("Updated" 10 t nill updated nil)))
)
#+end_src

** Org mode

*** Set the org base directory

Set base directory where org mode can find the org files

If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!

#+begin_src emacs-lisp
(setq org-directory my/org-base-dir)
#+end_src

*** Org general settings

Hide the markers (*,_, ...) when making text bold/italic etc

#+begin_src emacs-lisp
(setq org-hide-emphasis-markers t)
#+end_src

<<org-duration-format>>Set the output of the duration format to =hours:min= so we can sum these later on in org tables. The default format when passing 24 hours is 1d .. As we need to sum the duration we need the actual hours.

#+begin_src emacs-lisp
(setq org-duration-format 'h:mm)
#+end_src

Use Org Log =done= to auto insert a 'CLOSED' property when changing state below the heading. This is used for =ox-hugo= that ox-hugo auto-sets the date field in the front-matter to the time stamp in that CLOSED property. For more information see [[https://ox-hugo.scripter.co/doc/org-capture-setup/][Org Hugo capture setup]].

#+begin_src emacs-lisp
(setq org-log-done 'time)
#+end_src

Set the default todo keywords

#+begin_src emacs-lisp
  (setq org-todo-keywords '((sequence "TODO(t)" "NEXT(n)" "WAITING(w)" "In Progress(p)" "SOMEDAY(s)" "|" "DONE(d)" "CANCELED(c)")))
#+end_src

Set the refile targets

#+begin_src emacs-lisp
  (setq org-refile-targets '((concat my/org-base-dir "inbox.org" :maxlevel . 2)))
#+end_src

With (setq org-tags-match-list-sublevels 'indented), a number of dots equal to the level will be prepended to each agenda line to indicate its level.

#+begin_src emacs-lisp
(after! org
  (setq org-tags-match-list-sublevels 'indented))
#+end_src

*** Org custom functions

**** Return a list of files that have clockable items

#+begin_src emacs-lisp
(defun clockable-files ()
  "Returns org files that contain clockable items"
  (directory-files-recursively (concat my/org-base-dir "journal/") ".org"))
#+end_src

#+RESULTS:
: clockable-files

**** Function to change the format of a duration to HH:MM

This function can be applied to a table. Using a =#+TBLFMT:=. I am using this function to enable [[https://github.com/tbanel/orgaggregate][Org Aggregate]] time duration sums. The expected format for the time durations is =HH:MM=.

Also check the correct setting for [[org-duration-format][org-duration-format]]

#+BEGIN_EXAMPLE
;; Convert the time strings in column $3 and place them in column $5, also set the header of column $5
#+TBLFM: $5='(convert-org-clocktable-time-to-hhmm $3)::@1$5='(format "%s" "T")
#+END_EXAMPLE

#+begin_src emacs-lisp
(defun convert-org-clocktable-time-to-hhmm (time-string)
  "Converts a time string to HH:MM"
  (if (> (length time-string) 0)
      (progn
        (let* ((s (s-replace "*" "" time-string))
               (splits (split-string s ":"))
               (hours (car splits))
               (minutes (car (last splits)))
               )
          (if (= (length hours) 1)
              (format "0%s:%s" hours minutes)
            (format "%s:%s" hours minutes))))
    time-string))
#+end_src

*** Org agenda

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-files (directory-files-recursively my/org-base-dir "\.org$")))

(defun org-agenda-inactive ()
  (interactive)
  (let ((org-agenda-include-inactive-timestamps t))
    (org-agenda)))

(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c b") 'org-agenda-inactive)
#+end_src

*** Org calendar

#+begin_src emacs-lisp
(after! org
  (setq calendar-week-start-day 1)
  (setq calendar-intermonth-text
        '(propertize
          (format "%2d"
                  (car
                   (calendar-iso-from-absolute
                    (calendar-absolute-from-gregorian (list month day year)))))
          'font-lock-face 'font-lock-warning-face))
  (setq calendar-intermonth-header
        (propertize "Wk"                  ; or e.g. "KW" in Germany
                    'font-lock-face 'font-lock-keyword-face)))
#+end_src

*** Org capture templates

Function that returns a Hugo post capture template.

#+begin_src emacs-lisp
(defun org-hugo-new-subtree-post-capture-template ()
  "Returns `org-capture' template string for new Hugo post.
   See `org-capture-templates' for more information."
  (let* ((title (read-from-minibuffer "Post Title: ")) ;Prompt to enter the post title
         (fname (org-hugo-slug title)))
    (mapconcat #'identity
               `(
                 ,(concat "* TODO " title)
                 ":PROPERTIES:"
                 ,(concat ":EXPORT_FILE_NAME: " fname)
                 ":END:"
                 "%?\n")          ;Place the cursor here finally
               "\n")))
#+end_src

Set the to be be used capture templates!

#+begin_src emacs-lisp
(after! org
  ;; clean the intial existing template list
  (setq org-capture-templates '())

  ;; add todo capture template
  (add-to-list 'org-capture-templates
               '("t"
                 "Todo [inbox]"
                 entry
                 (file+headline "inbox.org" "Inbox")
                 "* TODO %i%?"))

  ;; add hugo capture template
  (add-to-list 'org-capture-templates
               '("h"                ;`org-capture' binding + h
                 "Hugo post"
                 entry
                 ;; It is assumed that below file is present in `org-directory'
                 ;; and that it has a "Blog Ideas" heading. It can even be a
                 ;; symlink pointing to the actual location of all-posts.org!
                 (file+olp "~/Dropbox/notes/org/blog.org" "Posts")
                 (function org-hugo-new-subtree-post-capture-template) :prepend t)))
#+end_src

*** Org babel

#+begin_src emacs-lisp
(setq org-babel-clojure-backend 'cider)
#+end_src

*** Org bullets

Make sure we have nice bullets for org headings.
#+begin_src emacs-lisp
(setq org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿"))
#+end_src

*** Org journal

Set the location of the journal files.

#+begin_src emacs-lisp
(setq org-journal-dir (concat my/org-base-dir "journal"))
#+end_src

A better title for a journal entry, instead of using a top header with the date, we use the TITLE meta field.

#+begin_src emacs-lisp
(setq org-journal-date-prefix "#+TITLE: ")
#+end_src

Normally the hours level is a second level heading, change that to first level.

#+begin_src emacs-lisp
(setq org-journal-time-prefix "* ")
#+end_src

Use a better date format: day, year-month-day.

#+begin_src emacs-lisp
(setq org-journal-date-format "%a, %Y-%m-%d")
#+end_src

Set a good format for the journal file e.g. year-month-day with a .org extensions.

#+begin_src emacs-lisp
(setq org-journal-file-format "%Y-%m-%d.org")
#+end_src

*** Org roam

Set the default path to Org-roam files.

#+begin_src emacs-lisp
(setq org-roam-directory (concat my/org-base-dir "roam"))
#+end_src

If non-nil, open the org-roam buffer when opening an org roam file. I set it to nil so the roam buffer will not show every time i open a org file.

#+begin_src emacs-lisp
(setq +org-roam-open-buffer-on-find-file nil)
#+end_src

** Zoom window

Make it possible to zoom in/out the current window.

#+begin_src emacs-lisp
;; https://github.com/emacsorphanage/zoom-window
(custom-set-variables
 '(zoom-window-mode-line-color "purple"))
(map! :desc "Zoom/Unzoom the current window"
      :n "C-w C-z" 'zoom-window-zoom)
#+end_src

** Smartparens

Smartparens is a minor mode for dealing with pairs in Emacs.

#+begin_src emacs-lisp
(after! smartparens
  (add-hook! (clojure-mode emacs-lisp-mode lisp-mode cider-repl-mode) :append #'smartparens-strict-mode))
(map!
 :map smartparens-mode-map
 ;; smartparens maps (navigation ops)
 :nvie "C-M-f" #'sp-forward-sexp
 :nvie "C-M-b" #'sp-backward-sexp
 :nvie "C-M-u" #'sp-backward-up-sexp
 :nvie "C-M-d" #'sp-down-sexp
 ;; smartparens maps (split join slurp barf)
 :nie "M-s" #'sp-split-sexp
 :nie "M-j" #'sp-join-sexp
 :nvie "C->" #'sp-forward-slurp-sexp
 :nvie "C-<" #'sp-forward-barf-sexp
 :nvie "C-{" #'sp-backward-slurp-sexp
 :nvie "C-}" #'sp-backward-barf-sexp)
#+end_src

* General Programming
** CSS
Set default indentation for css to 2 spaces

#+begin_src emacs-lisp
(after! css-mode
  (setq css-indent-offset 2))
#+end_src
** JSON
Lets format JSON with a specific width

#+begin_src emacs-lisp
(setq json-reformat:indent-width 2)
#+end_src

*** =C-c C-f= Json beautify

#+begin_src emacs-lisp
(map! :desc "JSON beautify"
      :n "C-c C-f" 'json-mode-beautify)
#+end_src

** Markdown
#+begin_src emacs-lisp
(map! :localleader
      :map markdown-mode-map
      :prefix ("i" . "Insert")
      :desc "Blockquote"    "q" 'markdown-insert-blockquote
      :desc "Bold"          "b" 'markdown-insert-bold
      :desc "Code"          "c" 'markdown-insert-code
      :desc "Emphasis"      "e" 'markdown-insert-italic
      :desc "Footnote"      "f" 'markdown-insert-footnote
      :desc "Code Block"    "s" 'markdown-insert-gfm-code-block
      :desc "Image"         "i" 'markdown-insert-image
      :desc "Link"          "l" 'markdown-insert-link
      :desc "List Item"     "n" 'markdown-insert-list-item
      :desc "Pre"           "p" 'markdown-insert-pre
      (:prefix ("h" . "Headings")
        :desc "One"   "1" 'markdown-insert-header-atx-1
        :desc "Two"   "2" 'markdown-insert-header-atx-2
        :desc "Three" "3" 'markdown-insert-header-atx-3
        :desc "Four"  "4" 'markdown-insert-header-atx-4
        :desc "Five"  "5" 'markdown-insert-header-atx-5
        :desc "Six"   "6" 'markdown-insert-header-atx-6))
#+end_src

* Programming
** Cider
Make the Cider popup window appear in the right hand side.

#+begin_src emacs-lisp
(after! cider
  (set-popup-rule! "^\\*cider-repl" :side 'right :size 0.3 :quit nil :ttl 0))
#+end_src

** Clojure
