;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
;; (setq user-full-name "John Doe"
;;      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
;; (setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
;; (setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
;; (setq display-line-numbers-type t)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

(setq my/home-dir "~")
(setq my/org-base-dir (concat my/home-dir "/Dropbox/notes/org/"))

(setq user-full-name "Marco Pas")

(setq user-mail-address "marco.pasopas@gmail.com")

(setq auth-sources '("~/.authinfo"))

(setq confirm-kill-emacs nil)

(setq kill-whole-line t)

(map! :map evil-normal-state-map
      :desc "Close the current buffer"
      :ng "c" #'kill-this-buffer)

(map! :map evil-normal-state-map
      :desc "Cycle through windows"
      :ng "C-w C-w" #'evil-window-next)

(add-hook 'org-mode-hook (lambda ()
                           (define-key org-mode-map (kbd "C-c g") 'org-mac-grab-link)))

(defun insert-date (arg)
  (interactive "P")
  (insert (if arg
              (format-time-string "%d.%m.%Y")
            (format-time-string "%Y-%m-%d"))))

(defun insert-timestamp ()
  (interactive)
  (insert (format-time-string "%Y-%m-%dT%H:%M:%S")))

(defun jx/insert-custom-clock-entry ()
  (interactive)
  (insert "CLOCK: ")
  (org-time-stamp-inactive)
  (insert "--")
  ;; Inserts the current time by default.
  (let ((current-prefix-arg '(4))) (call-interactively 'org-time-stamp-inactive))
  (org-ctrl-c-ctrl-c))

                                        ; Shortcut
(define-key evil-normal-state-map (kbd "C-'") 'jx/insert-custom-clock-entry)
(define-key evil-insert-state-map (kbd "C-'") 'jx/insert-custom-clock-entry)

(setq my/insert-clipboard-image-use-headername t)

(setq my/insert-clipboard-image-use-buffername t)

;; Overview
;; --------
;; Inserts an image from the clipboard by prompting the user for a filename.
;; Default extension for the pasted filename is .png

;; A ./images directory will be created relative to the current Org-mode document to store the images.

;; The default name format of the pasted image is:
;; filename: <yyyymmdd>_<hhmmss>_-_<image-filename>.png

;; Important
;; --------
;; This function depends on 'pngpaste' to paste the clipboard image
;; -> $ brew install pngpaste

;; Basic Customization
;; -------------------
;; Include the current Org-mode header as part of the image name.
;; (setq my/insert-clipboard-image-use-headername t)
;; filename: <yyyymmdd>_<hhmmss>_-_<headername>_-_<image-filename>.png

;; Include the buffername as part of the image name.
;; (setq my/insert-clipboard-image-use-buffername t)
;; filename: <yyyymmdd>_<hhmmss>_-_<buffername>_-_<image-filename>.png

;; Full name format
;; filename: <yyyymmdd>_<hhmmss>_-_<buffername>_-_<headername>_-_<image-filename>.png
(defun my/insert-clipboard-image (filename)
  "Inserts an image from the clipboard"
  (interactive "sFilename to paste: ")
  (let ((file
         (concat
          (file-name-directory buffer-file-name)
          "images/"
          (format-time-string "%Y%m%d_%H%M%S_-_")
          (if (bound-and-true-p my/insert-clipboard-image-use-buffername)
              (concat (s-replace "-" "_"
                                 (downcase (file-name-sans-extension (buffer-name)))) "_-_")
            "")
          (if (bound-and-true-p my/insert-clipboard-image-use-headername)
              (concat (s-replace " " "_" (downcase (nth 4 (org-heading-components)))) "_-_")
            "")
          filename ".png")))

    ;; create images directory
    (unless (file-exists-p (file-name-directory file))
      (make-directory (file-name-directory file)))

    ;; paste file from clipboard
    (shell-command (concat "pngpaste " file))
    (insert (concat "[[./images/" (file-name-nondirectory file) "]]"))))

(map! :desc "Insert clipboard image"
      :n "C-M-y" 'my/insert-clipboard-image)

(add-to-list 'initial-frame-alist '(fullscreen . maximized))

(setq doom-theme 'doom-vibrant)
(setq doom-vibrant-brighter-comments t  ;; "If non-nil, more vivid colors will be used to style the mode-line."
      doom-vibrant-brighter-modeline t  ;; "If non-nil, comments will be highlighted in more vivid colors."
      doom-vibrant-comment-bg t)        ;; "If non-nil, comments will have a subtle, darker background. Enhancing their legibility."

(setq doom-font (font-spec :family "FiraCode Nerd Font Mono" :size 16))

(setq doom-variable-pitch-font (font-spec :family "Ubuntu" :size 14))

(setq doom-big-font (font-spec :family "FiraCode Nerd Font Mono" :size 30))

(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))

(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

(map! :leader
      :desc "Toggle truncate lines"
      "t t" #'toggle-truncate-lines)

(display-time-mode 1)
(setq display-time-day-and-date t)

(setq doom-modeline-vcs-max-length 80)

(after! doom-modeline
  (setq doom-modeline-bar-width 3))

(add-hook 'after-init-hook (lambda ()
  (when (fboundp 'auto-dim-other-buffers-mode)
    (auto-dim-other-buffers-mode t))))

(setq deft-directory my/org-base-dir
      deft-default-extension "org"
      deft-extensions '("txt" "md" "org")
      deft-recursive t
      deft-use-filename-as-title t
      deft-use-filter-string-for-filename t
      deft-file-naming-rules '((noslash . "-")
                               (nospace . "-")
                               (case-fn . downcase)))

(setq dired-dwim-target t)

;; (with-eval-after-load 'forge
;; Configure number of topics show, open and closed
;; use negative number to toggle the view of closed topics
;; using `forge-toggle-closed-visibility'
(setq  forge-topic-list-limit '(100 . -10))

;; set closed to 0 to never show closed issues
;; (setq  forge-topic-list-limit '(100 . 0))

(defun acg/parse-git-remote-url (url)
  "If necessary, convert an SSH to HTTPS git remote location."
  (if (string-match "^http" url)
      url
    (replace-regexp-in-string "\\(.*\\)@\\(.*\\):\\(.*\\)\\(\\.git?\\)"
                              "https://\\2/\\3"
                              url)))

(defun acg/magit-open-remote-repo ()
  "Opens a remote repo URL. Prompts the user to choose a remote."
  (interactive)
  (let* ((remote-name (magit-read-remote "Choose remote repository"))
         (url (magit-get "remote" remote-name "url")))
    (browse-url (acg/parse-git-remote-url url))
    (message "Opening repo %s" url)))

(defun acg/project-get-root-relative-path (&optional path)
  "Returns PATH relative to a project root."
  (let* ((path (expand-file-name (or path default-directory)))
         (root-path (expand-file-name
                     (cdr (project--find-in-directory path))))
         (root-length (length root-path))
         (rel-path (substring path root-length)))
    rel-path))

(defun acg/magit-open-remote-dwim (&optional dir)
  "Opens a remote repo URL in the exact DIR location. Prompts the user to choose a remote."
  (interactive)
  (let* ((file (buffer-file-name))
         (dir (expand-file-name (or dir default-directory)))
         (remote-name (magit-read-remote "Choose remote repository" nil t))
         (url (acg/parse-git-remote-url
               (magit-get "remote" remote-name "url")))
         ;; Identify remote hosting type (e.g., GitHub, GitLab, etc.)
         (remote-hosting-type
          (cond
           ((string-match-p (regexp-quote "github") url) "GitHub")
           ((string-match-p (regexp-quote "gitlab") url) "GitLab")
           (t (completing-read "Choose remote hosting type:"
                               '("GitHub" "GitLab"))))))
    ;; Adapt to GitLab's URL standard
    (when (string= remote-hosting-type "GitLab")
      (setq url (concat url "/-")))
    ;; Adapt to differences in file and directory URL paths
    (if file
        (setq url (concat url "/blob/" (magit-get-current-branch)
                          "/" (acg/project-get-root-relative-path file)))
      (setq url (concat url "/tree/" (magit-get-current-branch)
                        "/" (acg/project-get-root-relative-path dir))))
    ;; Perform actions
    (browse-url url)
    (message "Opening %s" url)))

(setq ob-mermaid-cli-path "/usr/local/bin/mmdc")

(setq org-directory my/org-base-dir)

(setq org-hide-emphasis-markers t)

(setq org-duration-format 'h:mm)

(setq org-log-done 'time)

(setq org-todo-keywords
      '((sequence "TODO" "DOING" "BLOCKED" "|" "DONE" "ARCHIVED")))

(setq org-refile-targets '((concat my/org-base-dir "inbox.org" :maxlevel . 2)))

(after! org
  (setq org-tags-match-list-sublevels 'indented))

(after! org
  (setq org-tags-column -120))

(after! org
  (setq org-agenda-prefix-format
        '((agenda . " %i %-12:c%?-12t% s")
          (todo   . " ")
          (tags   . " %i %-12:c")
          (search . " %i %-12:c"))))

(after! org
  (setq org-image-actual-width (/ (display-pixel-width) 2)))

(defun clockable-files ()
  "Returns org files that contain clockable items"
  (directory-files-recursively (concat my/org-base-dir "journal/") ".org"))

(defun convert-org-clocktable-time-to-hhmm (time-string)
  "Converts a time string to HH:MM"
  (if (> (length time-string) 0)
      (progn
        (let* ((s (s-replace "*" "" time-string))
               (splits (split-string s ":"))
               (hours (car splits))
               (minutes (car (last splits)))
               )
          (if (= (length hours) 1)
              (format "0%s:%s" hours minutes)
            (format "%s:%s" hours minutes))))
    time-string))

(setq org-agenda-hide-tags-regexp ".")

(after! org
  (setq org-agenda-files (list
                          (concat my/org-base-dir "inbox.org")
                          (concat my/org-base-dir "agenda.org"))))

(after! org
  (setq calendar-week-start-day 1)
  (setq calendar-intermonth-text
        '(propertize
          (format "%2d"
                  (car
                   (calendar-iso-from-absolute
                    (calendar-absolute-from-gregorian (list month day year)))))
          'font-lock-face 'font-lock-warning-face))
  (setq calendar-intermonth-header
        (propertize "Wk"                  ; or e.g. "KW" in Germany
                    'font-lock-face 'font-lock-keyword-face)))

(defun org-hugo-new-subtree-post-capture-template ()
  "Returns `org-capture' template string for new Hugo post.
   See `org-capture-templates' for more information."
  (let* ((title (read-from-minibuffer "Post Title: ")) ;Prompt to enter the post title
         (fname (org-hugo-slug title)))
    (mapconcat #'identity
               `(
                 ,(concat "* TODO " title)
                 ":PROPERTIES:"
                 ,(concat ":EXPORT_FILE_NAME: " fname)
                 ":END:"
                 "%?\n")          ;Place the cursor here finally
               "\n")))

(after! org
  ;; clean the intial existing template list
  (setq org-capture-templates '())


  ;; add inbox capture template
  (add-to-list 'org-capture-templates
               `("i" "Inbox" entry (file "inbox.org")
                 ,(concat "* TODO %?\n"
                          "/Entered on/ %U")))

  ;; add meeting capture template
  (add-to-list 'org-capture-templates
               `("m" "Meeting" entry (file+headline "agenda.org" "Planned")
                 ,(concat "* %? :meeting:\n"
                          "<%<%Y-%m-%d %a %H:00>>")))

  ;; add hugo capture template
  (add-to-list 'org-capture-templates
               '("h"                ;`org-capture' binding + h
                 "Hugo post"
                 entry
                 ;; It is assumed that below file is present in `org-directory'
                 ;; and that it has a "Blog Ideas" heading. It can even be a
                 ;; symlink pointing to the actual location of all-posts.org!
                 (file+olp "~/Dropbox/notes/org/blog.org" "Posts")
                 (function org-hugo-new-subtree-post-capture-template) :prepend t)))

(setq org-babel-clojure-backend 'cider)

(setq org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿"))

(setq org-journal-dir (concat my/org-base-dir "journal"))

(setq org-journal-date-prefix "#+TITLE: ")

(setq org-journal-time-prefix "* ")

(setq org-journal-date-format "%a, %Y-%m-%d")

(setq org-journal-file-format "%Y-%m-%d.org")

(setq org-journal-enable-agenda-integration t)

(setq org-journal-tag-persistent-alist '(
                                         ("@work" . ?w)
                                         ("@private" . ?p)
                                         ("fontys" . ?f)
                                         ("ctoprogram" . ?c)
                                         ("integrationlab" . ?i)
                                         ("swat" . ?s)
                                         ("interruption" . ?!)
                                         ("various" . ?v)
                                         ))

(setq org-roam-directory (concat my/org-base-dir "roam"))

(setq +org-roam-open-buffer-on-find-file nil)

;; https://github.com/emacsorphanage/zoom-window
(custom-set-variables
 '(zoom-window-mode-line-color "purple"))
(map! :desc "Zoom/Unzoom the current window"
      :n "C-w z" 'zoom-window-zoom)

(after! smartparens
  (add-hook! (clojure-mode emacs-lisp-mode lisp-mode cider-repl-mode) :append #'smartparens-strict-mode))
(map!
 :map smartparens-mode-map
 ;; smartparens maps (navigation ops)
 :nvie "C-M-f" #'sp-forward-sexp
 :nvie "C-M-b" #'sp-backward-sexp
 :nvie "C-M-u" #'sp-backward-up-sexp
 :nvie "C-M-d" #'sp-down-sexp
 ;; smartparens maps (split join slurp barf)
 :nie "M-s" #'sp-split-sexp
 :nie "M-j" #'sp-join-sexp
 :nvie "C->" #'sp-forward-slurp-sexp
 :nvie "C-<" #'sp-forward-barf-sexp
 :nvie "C-{" #'sp-backward-slurp-sexp
 :nvie "C-}" #'sp-backward-barf-sexp)

(after! css-mode
  (setq css-indent-offset 2))

(setq json-reformat:indent-width 2)

(map! :desc "JSON beautify"
      :n "C-c C-f" 'json-mode-beautify)

(map! :localleader
      :map markdown-mode-map
      :prefix ("i" . "Insert")
      :desc "Blockquote"    "q" 'markdown-insert-blockquote
      :desc "Bold"          "b" 'markdown-insert-bold
      :desc "Code"          "c" 'markdown-insert-code
      :desc "Emphasis"      "e" 'markdown-insert-italic
      :desc "Footnote"      "f" 'markdown-insert-footnote
      :desc "Code Block"    "s" 'markdown-insert-gfm-code-block
      :desc "Image"         "i" 'markdown-insert-image
      :desc "Link"          "l" 'markdown-insert-link
      :desc "List Item"     "n" 'markdown-insert-list-item
      :desc "Pre"           "p" 'markdown-insert-pre
      (:prefix ("h" . "Headings")
        :desc "One"   "1" 'markdown-insert-header-atx-1
        :desc "Two"   "2" 'markdown-insert-header-atx-2
        :desc "Three" "3" 'markdown-insert-header-atx-3
        :desc "Four"  "4" 'markdown-insert-header-atx-4
        :desc "Five"  "5" 'markdown-insert-header-atx-5
        :desc "Six"   "6" 'markdown-insert-header-atx-6))

(after! cider
  (set-popup-rule! "^\\*cider-repl" :side 'right :size 0.3 :quit nil :ttl 0))
