[tools]
"github:sxyazi/yazi" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
adr-tools = "latest"
age = "latest"
aws = { version = "latest", symlink_bins = "true" }
bat = "latest"
cf = "latest"
chezmoi = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gopass = "latest"
granted = "latest"
httpie-go = "latest"
hurl = "latest"
jjui = "latest"
jq = "latest"
jujutsu = "latest"
just = "latest"
node = "22"
ollama = "latest"
pre-commit = "latest"
python = "3.13"
ripgrep = "latest"
rust = "1.94.0"
terraform = "latest"
terraform-docs = "latest"
tlrc = "latest"
uv = "latest"
yq = "latest"
difftastic = "latest"
"github:sethvargo/ratchet" = "latest"
github-cli = "latest"
terragrunt = "latest"

[settings]
idiomatic_version_file_enable_tools = []

[tools."github:terrastruct/d2"]
version = "latest"
bin_path = "d2-v{version}/bin"
filter_bins = "d2"

