# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$kubernetes\
$conda\
$python\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$docker_context\
$line_break\
$character
"""

# Inserts a blank line between shell prompts
add_newline = true

[docker_context]
disabled = false
only_with_files = false
format = 'via [🐋 $context](blue bold)'

[kubernetes]
disabled = false
detect_files = ['k8s']
format = 'on [☸️  ($user on )($cluster in )$context \($namespace\)](dimmed green) '

[conda]
format = "[$symbol$environment]($style) "

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[python]
pyenv_version_name = false
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
